sqlRepository:
  host: "localhost"
  port: 5432
  db: "anti_bruteforce"
  user: "user"
  password: "pass"

inMemoryRepository:
  addr: "localhost:6379"
  password: ""
  db: 0

grpcServer:
  host: "localhost"
  port: 50051
