// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: anti_bruteforce.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsCanLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCanLoginRequest) Reset() {
	*x = IsCanLoginRequest{}
	mi := &file_anti_bruteforce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCanLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCanLoginRequest) ProtoMessage() {}

func (x *IsCanLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCanLoginRequest.ProtoReflect.Descriptor instead.
func (*IsCanLoginRequest) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{0}
}

func (x *IsCanLoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *IsCanLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *IsCanLoginRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type IsCanLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCanLoginResponse) Reset() {
	*x = IsCanLoginResponse{}
	mi := &file_anti_bruteforce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCanLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCanLoginResponse) ProtoMessage() {}

func (x *IsCanLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCanLoginResponse.ProtoReflect.Descriptor instead.
func (*IsCanLoginResponse) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{1}
}

func (x *IsCanLoginResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ClearBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBucketRequest) Reset() {
	*x = ClearBucketRequest{}
	mi := &file_anti_bruteforce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBucketRequest) ProtoMessage() {}

func (x *ClearBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBucketRequest.ProtoReflect.Descriptor instead.
func (*ClearBucketRequest) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{2}
}

func (x *ClearBucketRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ClearBucketRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ClearBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBucketResponse) Reset() {
	*x = ClearBucketResponse{}
	mi := &file_anti_bruteforce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBucketResponse) ProtoMessage() {}

func (x *ClearBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBucketResponse.ProtoReflect.Descriptor instead.
func (*ClearBucketResponse) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{3}
}

func (x *ClearBucketResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ClearBucketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddCIDRToBlackListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCIDRToBlackListRequest) Reset() {
	*x = AddCIDRToBlackListRequest{}
	mi := &file_anti_bruteforce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCIDRToBlackListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCIDRToBlackListRequest) ProtoMessage() {}

func (x *AddCIDRToBlackListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCIDRToBlackListRequest.ProtoReflect.Descriptor instead.
func (*AddCIDRToBlackListRequest) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{4}
}

func (x *AddCIDRToBlackListRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type AddCIDRToBlackListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCIDRToBlackListResponse) Reset() {
	*x = AddCIDRToBlackListResponse{}
	mi := &file_anti_bruteforce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCIDRToBlackListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCIDRToBlackListResponse) ProtoMessage() {}

func (x *AddCIDRToBlackListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCIDRToBlackListResponse.ProtoReflect.Descriptor instead.
func (*AddCIDRToBlackListResponse) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{5}
}

func (x *AddCIDRToBlackListResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddCIDRToBlackListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteCIDRFromBlackListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCIDRFromBlackListRequest) Reset() {
	*x = DeleteCIDRFromBlackListRequest{}
	mi := &file_anti_bruteforce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCIDRFromBlackListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCIDRFromBlackListRequest) ProtoMessage() {}

func (x *DeleteCIDRFromBlackListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCIDRFromBlackListRequest.ProtoReflect.Descriptor instead.
func (*DeleteCIDRFromBlackListRequest) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCIDRFromBlackListRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type DeleteCIDRFromBlackListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCIDRFromBlackListResponse) Reset() {
	*x = DeleteCIDRFromBlackListResponse{}
	mi := &file_anti_bruteforce_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCIDRFromBlackListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCIDRFromBlackListResponse) ProtoMessage() {}

func (x *DeleteCIDRFromBlackListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCIDRFromBlackListResponse.ProtoReflect.Descriptor instead.
func (*DeleteCIDRFromBlackListResponse) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCIDRFromBlackListResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteCIDRFromBlackListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddCIDRToWhiteListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCIDRToWhiteListRequest) Reset() {
	*x = AddCIDRToWhiteListRequest{}
	mi := &file_anti_bruteforce_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCIDRToWhiteListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCIDRToWhiteListRequest) ProtoMessage() {}

func (x *AddCIDRToWhiteListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCIDRToWhiteListRequest.ProtoReflect.Descriptor instead.
func (*AddCIDRToWhiteListRequest) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{8}
}

func (x *AddCIDRToWhiteListRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type AddCIDRToWhiteListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCIDRToWhiteListResponse) Reset() {
	*x = AddCIDRToWhiteListResponse{}
	mi := &file_anti_bruteforce_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCIDRToWhiteListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCIDRToWhiteListResponse) ProtoMessage() {}

func (x *AddCIDRToWhiteListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCIDRToWhiteListResponse.ProtoReflect.Descriptor instead.
func (*AddCIDRToWhiteListResponse) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{9}
}

func (x *AddCIDRToWhiteListResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddCIDRToWhiteListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteCIDRFromWhiteListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCIDRFromWhiteListRequest) Reset() {
	*x = DeleteCIDRFromWhiteListRequest{}
	mi := &file_anti_bruteforce_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCIDRFromWhiteListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCIDRFromWhiteListRequest) ProtoMessage() {}

func (x *DeleteCIDRFromWhiteListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCIDRFromWhiteListRequest.ProtoReflect.Descriptor instead.
func (*DeleteCIDRFromWhiteListRequest) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCIDRFromWhiteListRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type DeleteCIDRFromWhiteListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCIDRFromWhiteListResponse) Reset() {
	*x = DeleteCIDRFromWhiteListResponse{}
	mi := &file_anti_bruteforce_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCIDRFromWhiteListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCIDRFromWhiteListResponse) ProtoMessage() {}

func (x *DeleteCIDRFromWhiteListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCIDRFromWhiteListResponse.ProtoReflect.Descriptor instead.
func (*DeleteCIDRFromWhiteListResponse) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCIDRFromWhiteListResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteCIDRFromWhiteListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_anti_bruteforce_proto protoreflect.FileDescriptor

const file_anti_bruteforce_proto_rawDesc = "" +
	"\n" +
	"\x15anti_bruteforce.proto\x12\x0fanti_bruteforce\"U\n" +
	"\x11isCanLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"$\n" +
	"\x12isCanLoginResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\":\n" +
	"\x12clearBucketRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"?\n" +
	"\x13clearBucketResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x19AddCIDRToBlackListRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"F\n" +
	"\x1aAddCIDRToBlackListResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x1eDeleteCIDRFromBlackListRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"K\n" +
	"\x1fDeleteCIDRFromBlackListResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x19AddCIDRToWhiteListRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"F\n" +
	"\x1aAddCIDRToWhiteListResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x1eDeleteCIDRFromWhiteListRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"K\n" +
	"\x1fDeleteCIDRFromWhiteListResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa2\x05\n" +
	"\x15AntiBruteforceService\x12U\n" +
	"\n" +
	"isCanLogin\x12\".anti_bruteforce.isCanLoginRequest\x1a#.anti_bruteforce.isCanLoginResponse\x12X\n" +
	"\vclearBucket\x12#.anti_bruteforce.clearBucketRequest\x1a$.anti_bruteforce.clearBucketResponse\x12m\n" +
	"\x12AddCIDRToWhiteList\x12*.anti_bruteforce.AddCIDRToWhiteListRequest\x1a+.anti_bruteforce.AddCIDRToWhiteListResponse\x12m\n" +
	"\x12AddCIDRToBlackList\x12*.anti_bruteforce.AddCIDRToBlackListRequest\x1a+.anti_bruteforce.AddCIDRToBlackListResponse\x12|\n" +
	"\x17DeleteCIDRFromBlackList\x12/.anti_bruteforce.DeleteCIDRFromBlackListRequest\x1a0.anti_bruteforce.DeleteCIDRFromBlackListResponse\x12|\n" +
	"\x17DeleteCIDRFromWhiteList\x12/.anti_bruteforce.DeleteCIDRFromWhiteListRequest\x1a0.anti_bruteforce.DeleteCIDRFromWhiteListResponseB.Z,github.com/gkarman/anti_bruteforce/api/pb;pbb\x06proto3"

var (
	file_anti_bruteforce_proto_rawDescOnce sync.Once
	file_anti_bruteforce_proto_rawDescData []byte
)

func file_anti_bruteforce_proto_rawDescGZIP() []byte {
	file_anti_bruteforce_proto_rawDescOnce.Do(func() {
		file_anti_bruteforce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anti_bruteforce_proto_rawDesc), len(file_anti_bruteforce_proto_rawDesc)))
	})
	return file_anti_bruteforce_proto_rawDescData
}

var file_anti_bruteforce_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_anti_bruteforce_proto_goTypes = []any{
	(*IsCanLoginRequest)(nil),               // 0: anti_bruteforce.isCanLoginRequest
	(*IsCanLoginResponse)(nil),              // 1: anti_bruteforce.isCanLoginResponse
	(*ClearBucketRequest)(nil),              // 2: anti_bruteforce.clearBucketRequest
	(*ClearBucketResponse)(nil),             // 3: anti_bruteforce.clearBucketResponse
	(*AddCIDRToBlackListRequest)(nil),       // 4: anti_bruteforce.AddCIDRToBlackListRequest
	(*AddCIDRToBlackListResponse)(nil),      // 5: anti_bruteforce.AddCIDRToBlackListResponse
	(*DeleteCIDRFromBlackListRequest)(nil),  // 6: anti_bruteforce.DeleteCIDRFromBlackListRequest
	(*DeleteCIDRFromBlackListResponse)(nil), // 7: anti_bruteforce.DeleteCIDRFromBlackListResponse
	(*AddCIDRToWhiteListRequest)(nil),       // 8: anti_bruteforce.AddCIDRToWhiteListRequest
	(*AddCIDRToWhiteListResponse)(nil),      // 9: anti_bruteforce.AddCIDRToWhiteListResponse
	(*DeleteCIDRFromWhiteListRequest)(nil),  // 10: anti_bruteforce.DeleteCIDRFromWhiteListRequest
	(*DeleteCIDRFromWhiteListResponse)(nil), // 11: anti_bruteforce.DeleteCIDRFromWhiteListResponse
}
var file_anti_bruteforce_proto_depIdxs = []int32{
	0,  // 0: anti_bruteforce.AntiBruteforceService.isCanLogin:input_type -> anti_bruteforce.isCanLoginRequest
	2,  // 1: anti_bruteforce.AntiBruteforceService.clearBucket:input_type -> anti_bruteforce.clearBucketRequest
	8,  // 2: anti_bruteforce.AntiBruteforceService.AddCIDRToWhiteList:input_type -> anti_bruteforce.AddCIDRToWhiteListRequest
	4,  // 3: anti_bruteforce.AntiBruteforceService.AddCIDRToBlackList:input_type -> anti_bruteforce.AddCIDRToBlackListRequest
	6,  // 4: anti_bruteforce.AntiBruteforceService.DeleteCIDRFromBlackList:input_type -> anti_bruteforce.DeleteCIDRFromBlackListRequest
	10, // 5: anti_bruteforce.AntiBruteforceService.DeleteCIDRFromWhiteList:input_type -> anti_bruteforce.DeleteCIDRFromWhiteListRequest
	1,  // 6: anti_bruteforce.AntiBruteforceService.isCanLogin:output_type -> anti_bruteforce.isCanLoginResponse
	3,  // 7: anti_bruteforce.AntiBruteforceService.clearBucket:output_type -> anti_bruteforce.clearBucketResponse
	9,  // 8: anti_bruteforce.AntiBruteforceService.AddCIDRToWhiteList:output_type -> anti_bruteforce.AddCIDRToWhiteListResponse
	5,  // 9: anti_bruteforce.AntiBruteforceService.AddCIDRToBlackList:output_type -> anti_bruteforce.AddCIDRToBlackListResponse
	7,  // 10: anti_bruteforce.AntiBruteforceService.DeleteCIDRFromBlackList:output_type -> anti_bruteforce.DeleteCIDRFromBlackListResponse
	11, // 11: anti_bruteforce.AntiBruteforceService.DeleteCIDRFromWhiteList:output_type -> anti_bruteforce.DeleteCIDRFromWhiteListResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_anti_bruteforce_proto_init() }
func file_anti_bruteforce_proto_init() {
	if File_anti_bruteforce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anti_bruteforce_proto_rawDesc), len(file_anti_bruteforce_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anti_bruteforce_proto_goTypes,
		DependencyIndexes: file_anti_bruteforce_proto_depIdxs,
		MessageInfos:      file_anti_bruteforce_proto_msgTypes,
	}.Build()
	File_anti_bruteforce_proto = out.File
	file_anti_bruteforce_proto_goTypes = nil
	file_anti_bruteforce_proto_depIdxs = nil
}
