name: anti bruteforce tests

on:
  push:
    branches:
      - "*"

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.63.4

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run unit tests with race detector and 100 runs
        run: go test -v -race -count=100 -timeout=5m ./...
